<?php

namespace AppBundle\Repository;

/**
 * AtoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtoutRepository extends \Doctrine\ORM\EntityRepository
{
}
