<?php

namespace AppBundle\Repository;

/**
 * DeveloppementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloppementRepository extends \Doctrine\ORM\EntityRepository
{
}
