<?php

namespace AppBundle\Repository;

/**
 * EventAleatoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAleatoireRepository extends \Doctrine\ORM\EntityRepository
{
}
