<?php

namespace AppBundle\Repository;

/**
 * FacteurGainTotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacteurGainTotalRepository extends \Doctrine\ORM\EntityRepository
{
}
