<?php

namespace AppBundle\Repository;

/**
 * FacteurPollutionGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacteurPollutionGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
