<?php

namespace AppBundle\Repository;

/**
 * FacteurInflationGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacteurInflationGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
