<?php

namespace AppBundle\Repository;

/**
 * InfobulleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfobulleRepository extends \Doctrine\ORM\EntityRepository
{
}
