<?php

namespace AppBundle\Repository;

/**
 * NiveauPollutionGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauPollutionGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
