<?php

namespace AppBundle\Repository;

/**
 * personnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personnageRepository extends \Doctrine\ORM\EntityRepository
{
}
