<?php

namespace AppBundle\Repository;

/**
 * TypeDeveloppementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeveloppementRepository extends \Doctrine\ORM\EntityRepository
{
}
