<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYrdox1p\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYrdox1p/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYrdox1p.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYrdox1p\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYrdox1p\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Yrdox1p',
    'container.build_id' => '8efcfce5',
    'container.build_time' => 1531380487,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYrdox1p');
