<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFok9cap\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFok9cap/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFok9cap.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFok9cap\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFok9cap\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fok9cap',
    'container.build_id' => '4a812a08',
    'container.build_time' => 1531339983,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFok9cap');
